name = "lawgpt-search"

main = "src/worker.ts"

compatibility_date = "2024-11-06"

[vars]
ENVIRONMENT = "production"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE"
index_name = "lawgpt-vector2"

[[d1_databases]]
binding = "DB"
database_name = "lawgpt-d1"
database_id = "4d20edf7-a77b-4ef0-b46a-01c84469569f"